### ISSUE TITLE
/dev/caam_kb: no such file or directory

### ISSUE THREAD

**Issue by OmarAberkan** [usbarmory/caam-keyblob#2]
caam_tool enc key key.blob
caam_tool: encrypting 7 bytes from key
caam_tool: error, open /dev/caam_kb: no such file or directory

KERNEL: 4.1.38-rt45-fslc

Installed files: 

/
├── etc
│   ├── modprobe.d
│   └── modules-load.d
├── lib
│   └── modules
│       └── 4.1.38-rt45-fslc+gee67fc7
│           └── extra
│               └── caam_keyblob.ko
└── usr
    ├── include
    │   └── caam-keyblob-mod
    │       └── Module.symvers
    └── sbin
        └── caam_tool

lsmod

Module                  Size  Used by
evbug                   1878  0
nfsd                  229204  1
auth_rpcgss       46126  1 nfsd
lockd                  61833  1 nfsd
grace                   2019  2 nfsd,lockd
sunrpc             215025  3 nfsd,auth_rpcgss,lockd
caam_keyblob    7427   0

modinfo caam_keyblob

filename:       /lib/modules/4.1.38-rt45-fslc+gee67fc7/extra/caam_keyblob.ko
author:         Freescale Semiconductor - NMSG/MAD
description:    FSL CAAM Secure Memory / Keystore
license:        Dual BSD/GPL
srcversion:     286E0876AAE8050A34E19A1
alias:          of:N*T*Cfsl,sec4.0-keyblob*
alias:          of:N*T*Cfsl,sec-v4.0-keyblob*
depends:        
vermagic:       4.1.38-rt45-fslc+gee67fc7 SMP preempt mod_unload modversions ARMv7 p2v8

**Comment by abarisani** [comment]
On which hardware platform are you executing this?

**Comment by OmarAberkan** [comment]
IMX6UL evaluation kit

**Comment by abarisani** [comment]
Can you show me the dmesg messages after loading the kernel module? (e.g. unload the module, clear the buffer with `dmesg -c`, load the module, show me the output of `dmesg`).

**Comment by OmarAberkan** [comment]
IMX6UL evaluation kit

**Comment by OmarAberkan** [comment]
It only shows that systemd loaded the module at boot, it shows nothing else.

**Comment by abarisani** [comment]
You should be able to see `caam_keyblob` related messages, even in case of failures. Please try and follow the procedure I laid out to try loading the module post boot and see which logs you see running `dmesg` (as root) but by clearing its buffer before (`dmesg -c`).

Additionally which distribution are you using? You must ensure that the caam hardware is present in the DTS file for the compiled kernel:

crypto: caam@2140000 {
                       compatible = "fsl,imx6ul-caam", "fsl,sec-v4.0";

**Comment by abarisani** [comment]
As reference here's what you should see on a successful loading of the caamg_keyblob module:

```
# modprobe caam_keyblob
# dmesg 
[   94.757330] caam 2140000.caam: Entropy delay = 3200
[   94.757375] caam 2140000.caam: Instantiated RNG4 SH0
[   94.822133] caam 2140000.caam: Instantiated RNG4 SH1
[   94.822344] caam 2140000.caam: device ID = 0x0a16030000000000 (Era -524)
[   94.822364] caam 2140000.caam: job rings = 3, qi = 0, dpaa2 = no
[   94.859093] caam_keyblob caam-keyblob: caam keyblob initialized
```
Please note that you need the vanilla CAAM and CAAM Job Ring drivers in your kernel configuration:

```
 CRYPTO_DEV_FSL_CAAM=m
 CRYPTO_DEV_FSL_CAAM_JR=m
```

The DTS CAAM configuration has been added April 2018 in vanilla kernels, therefore you will find it in DTS files on kernels >= 4.18.

**Comment by abarisani** [comment]
I updated our documentation to better clarify this aspect, see https://github.com/inversepath/caam-keyblob/commit/6500c585bd81dac71c09627167b657cf66999f4d

I am closing this issue, please re-open it if necessary.
