### ISSUE TITLE
GPLv2 Relicensing

### ISSUE THREAD

**Issue by smipi1** [usbarmory/caam-keyblob#3]
Can you add a GPLv2 licensing option or a tivoization exemption on the GPLv3 license in use?

We would like to use this code to create a secure device with high integrity guarantees. Such guarantees cannot be implemented with a GPLv3 license without a tivoization exemption.

**Comment by smipi1** [comment]
Hi @abarisani, @danbia or @andrejro,

Can you comment on this?

**Comment by abarisani** [comment]
Can you please contact me privately about this with an explanation of your secure device context and licensing? Thanks!

**Comment by abarisani** [comment]
We received no private contact on this matter yet, please do so if this is still a concern and I'd be happy to discuss it.
