### ISSUE TITLE
Driver is not working

### ISSUE THREAD

**Issue by embetrix** [usbarmory/caam-keyblob#5]
Hello,

first of all many thanks for publishing this tool.

I sadly got not chance make it working on a imx6UL 

* My HW is a Phytec phyBOARD-Segin i.MX6 UltraLite Full Featured
*  Mainline Kernel from https://github.com/torvalds/linux version 5.1.0-rc1

CAAM support is enabled 
```
root@imx6ul-scu:~# zcat /proc/config.gz | grep CAAM
CONFIG_CRYPTO_DEV_FSL_CAAM_COMMON=y
CONFIG_CRYPTO_DEV_FSL_CAAM=y
CONFIG_CRYPTO_DEV_FSL_CAAM_JR=y
CONFIG_CRYPTO_DEV_FSL_CAAM_RINGSIZE=9
CONFIG_CRYPTO_DEV_FSL_CAAM_CRYPTO_API=y
CONFIG_CRYPTO_DEV_FSL_CAAM_AHASH_API=y
CONFIG_CRYPTO_DEV_FSL_CAAM_PKC_API=y
CONFIG_CRYPTO_DEV_FSL_CAAM_RNG_API=y
CONFIG_CRYPTO_DEV_FSL_CAAM_CRYPTO_API_DESC=y
CONFIG_CRYPTO_DEV_FSL_CAAM_AHASH_API_DESC=y
```
```
root@imx6ul-scu:~# dmesg | grep caam
[    1.839186] caam 2140000.caam: Entropy delay = 3200
[    1.844294] caam 2140000.caam: Instantiated RNG4 SH0
[    1.905057] caam 2140000.caam: Instantiated RNG4 SH1
[    1.910109] caam 2140000.caam: device ID = 0x0a16030000000000 (Era 8)
[    1.916579] caam 2140000.caam: job rings = 3, qi = 0
[    2.002691] caam algorithms registered in /proc/crypto
[    2.019268] caam_jr 2141000.jr0: registering rng-caam
[    2.025554] caam 2140000.caam: caam pkc algorithms registered in /proc/crypto
```
Loading the module output only this out:
```
root@imx6ul-scu:~# insmod caam_keyblob.ko 
[  625.928605] caam_keyblob: loading out-of-tree module taints kernel.
```
```
root@imx6ul-scu:~# lsmod
Module                  Size  Used by
caam_keyblob           20480  0
```

Device Node is not present!

When trying with caam_tool:
```
root@imx6ul-scu:~# ./caam_tool enc file.in file.enc
caam_tool: encrypting 12 bytes from file.in
caam_tool: error, open /dev/caam_kb: no such file or directory
```

it's pretty much the same what previous user reported as bug.

BR

**Comment by OmarAberkan** [comment]
I had the exact same problem:
https://github.com/inversepath/caam-keyblob/issues/4

**Comment by OmarAberkan** [comment]
This is indeed the same problem that i had. I never got it working.

**Comment by abarisani** [comment]
I'll investigate this further with more recent kernel and check what's happening. We have it working on earlier version so maybe something changed in the way the character device is created, I'll get back to you. Thanks for your patience.

**Comment by embetrix** [comment]
@abarisani , I tested it with 4.14 Kernel and I got the same results. 
something is missing in the description maybe ?
I would suspect that the driver ".compatible" section : https://github.com/inversepath/caam-keyblob/blob/master/caam_keyblob.c#L684 is something wrong.
should the compatibility  "fsl,sec-v4.0-keyblob" defined in DTS ?
Thank you

**Comment by abarisani** [comment]
You might be right, looks like I overlooked that.

We do have the right DTS in our buildroot profile, but the relevant entry is not included in vanilla kernels.

Please check the following file:

https://github.com/inversepath/usbarmory/blob/master/software/kernel_conf/imx6ul-pico/imx6ul-pico-hobbit-caam.dts

Can you please re-compile your kernel with the following patch (you might need to adapt it)?

```
diff -uarN a/arch/arm/boot/dts/imx6ul-pico-hobbit.dts b/arch/arm/boot/dts/imx6ul-pico-hobbit.dts
--- a/arch/arm/boot/dts/imx6ul-pico-hobbit.dts  2018-08-24 13:09:23.000000000 +0200
+++ b/arch/arm/boot/dts/imx6ul-pico-hobbit.dts  2018-09-03 15:43:55.228645226 +0200
@@ -59,6 +59,11 @@
                stdout-path = &uart6;
        };
 
+       caam_keyblob: caam-keyblob {
+               compatible = "fsl,sec-v4.0-keyblob";
+               status = "okay";
+       };
+
        backlight {
                compatible = "pwm-backlight";
                pwms = <&pwm3 0 5000000>;
```

I will fix the documentation once you confirm this is the only section that needs to be added in this repository documentation.

Thanks

**Comment by embetrix** [comment]
@abarisani : yes indeed that did the trick ! 
it is working now:
```
[  103.605769] caam_keyblob: disagrees about version of symbol module_layout
[  118.365050] caam_keyblob: loading out-of-tree module taints kernel.
[  118.381312] caam_keyblob caam-keyblob: caam_keyblob: initialized
[  118.387382] caam_keyblob: WARNING - not in Trusted or Secure State, Non-volatile test key in effect
```

Encryption/Decryption seems to be working fine:

```
root@imx6ul-scu:~/caam# echo "secret" > file

root@imx6ul-scu:~/caam# ./caam_tool enc file file.enc
caam_tool: encrypting 7 bytes fro[  412.022691] caam_keyblob: kb_ioctl rawkey_len:7 keyblob_len:55
m file
caam_tool: caam_kb_data &amp;{Text:0x11d5c000 TextLen:7 Blob:0x11d40080 BlobLen:55 Keymod:0x11d120b0 KeymodLen:16}
caam_tool: issuing ioctl c0184900 on /dev/caam_kb
caam_tool: encrypted 55 bytes to file.enc

root@imx6ul-scu:~/caam# ./caam_tool dec file.dec file.enc                                                                                                                                                          
caam_tool: decrypting 55 bytes from file.enc
[  428.140501] caam_keyblob: kb_ioctl rawkey_len:7 keyblob_len:55
caam_tool: caam_kb_data &amp;{Text:0x111120d0 TextLen:7 Blob:0x1115c000 BlobLen:55 Keymod:0x111120b0 KeymodLen:16}
caam_tool: issuing ioctl c0184901 on /dev/caam_kb
caam_tool: decrypted 7 bytes to file.dec

root@imx6ul-scu:~/caam# diff -q file file.dec
```

Thank you very much for the support !!!!

**Comment by OmarAberkan** [comment]
Nice! This patch should be added to the documentation.

**Comment by abarisani** [comment]
I am tempted to just modify the driver with this:

```
diff --git a/caam_keyblob.c b/caam_keyblob.c
index 6687ad3..ae5e179 100644
--- a/caam_keyblob.c
+++ b/caam_keyblob.c
@@ -683,10 +683,10 @@ static int caam_keyblob_remove(struct platform_device *pdev)
 
 static struct of_device_id caam_keyblob_match[] = {
 	{
-		.compatible = "fsl,sec-v4.0-keyblob",
+		.compatible = "fsl,sec-v4.0",
 	},
 	{
-		.compatible = "fsl,sec4.0-keyblob",
+		.compatible = "fsl,sec4.0",
 	},
 	{},
 };
```

As I see little sense in having a separate DTS entry for the "keyblob" functionality (the CAAM and keyblob functionality are not distinct, you cannot have a CAAM without keyblob support).

Would you mind testing this as well?

This way I would not have to change documentation or requiring users to change DTS on Vanilla kernels.

**Comment by embetrix** [comment]
This was the first thing I did tried, it does not work.

**Comment by abarisani** [comment]
Please let me know if https://github.com/inversepath/caam-keyblob/commit/f692da2894618423b743ee32255ccdd3d0af314f is clear enough so that we can close this issue.

In the near future we will submit patches upstream to have such dts entries included by default.

Thanks!

**Comment by embetrix** [comment]
Looks fine to me.

Thank you!

**Comment by OmarAberkan** [comment]
Thanks!
