### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by OmarAberkan** [usbarmory/caam-keyblob#9]
https://github.com/inversepath/usbarmory/blob/master/software/kernel_conf/imx6ul-pico/imx6ul-pico-hobbit-caam.dts

This link in the documentation doesn't exist anymore.

**Comment by abarisani** [comment]
Thanks for spotting this, fixed in https://github.com/inversepath/caam-keyblob/commit/9ffcb19fba5f9c510c59c805191f8050c4d84889
